import { Alert } from '@/components/ui'
import { LegalDoc, LegalSection } from '@/features/marketing/components'
import { useDocumentTitle } from '@/hooks'

export default function LegalTermsPage() {
  useDocumentTitle('Terms')

  return (
    <LegalDoc
      title="Terms of use"
      updated="2026-08-30"
      summary="The short version: your documents stay yours, answers are a starting point rather than a verdict, and the service is a preview."
    >
      <Alert tone="warning" title="Not reviewed by a lawyer">
        These terms describe the intended arrangement in plain language. They have not been drafted or
        reviewed by counsel and must be replaced before the product is sold.
      </Alert>

      <LegalSection id="your-content" heading="Your documents remain yours">
        <p>
          Uploading a file grants us only what is needed to run the service: to extract its text,
          create embeddings from it, store those alongside your workspace, and return passages from it
          to you. Nothing you upload is used to train a model, sold, or shown to another workspace.
        </p>
        <p>
          You are responsible for having the right to upload what you upload. If a document contains
          someone else's confidential or personal information, that obligation follows it here.
        </p>
      </LegalSection>

      <LegalSection id="answers" heading="An answer is evidence, not advice">
        <p>
          Answers are generated by a language model from passages retrieved out of your own documents.
          The model can misread a passage, miss a clause that retrieval did not surface, or summarise
          two sources into something neither says. That is why every answer carries its sources: the
          citation is the part you should rely on.
        </p>
        <p>
          Do not treat output as legal, medical, financial or safety advice, and do not act on a
          material decision without reading the cited passage.
        </p>
      </LegalSection>

      <LegalSection id="acceptable-use" heading="What not to do with it">
        <ul className="ml-5 flex list-disc flex-col gap-1.5">
          <li>Do not upload content you have no right to process.</li>
          <li>
            Do not attempt to reach another workspace's documents, or to use a workspace API key
            outside the workspace it was issued for.
          </li>
          <li>
            Do not use the service to build a competing index of third-party material you do not own.
          </li>
          <li>
            Do not run load against it that a normal reader would not — the upload and query paths are
            rate limited, and circumventing those limits is not permitted.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="availability" heading="Availability and changes">
        <p>
          This is a preview. Features can change, endpoints that do not exist yet may arrive, and
          there is no uptime commitment. Anything that would delete your documents will be announced
          before it happens.
        </p>
        <p>
          The service is currently free, and no charge can be applied without you agreeing to a price
          first — there is no payment provider connected to it.
        </p>
      </LegalSection>

      <LegalSection id="ending" heading="Ending it">
        <p>
          You can stop using DocMind at any time; ask us to remove your workspace and its vectors go
          with it. We may suspend an account that is being used to harm the service or another
          workspace, and will say why.
        </p>
      </LegalSection>
    </LegalDoc>
  )
}
